[package]
name = "future-combinators"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
async-std = { version = "1.11.0", features = ["attributes"] }
